name: build-docs

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint frontmatter (books)
        run: |
          python tools/scripts/lint-frontmatter.py

      - name: Build portal (generate hub pages)
        run: |
          python tools/scripts/build-portal.py

      # TODO: Replace with real static site build (MkDocs/Docusaurus) later
      - name: Placeholder docs build
        run: echo "Docs build placeholder – portal generator ran successfully."
